active_profile = "default"

[profile.default]
platform = "snowflake"
authenticator = "username_password_mfa"
password = "R@my2067416920"
passcode = "592362"
user = "RAMY"
account = "NDSOEBE-RAI_FIELD"
role = "ACCOUNTADMIN"
warehouse = "W_WAREHOUSE"
rai_app_name = "RELATIONALAI"
engine = ""
engine_size = "HIGHMEM_X64_S"



